spring:
  application:
    name: tellar-banking-bff
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
#  flyway:
#    locations: classpath:db\migration
#    baseline-on-migrate: true
#    enabled: true
tellar:
  credit-balance:
    default-amount: 1000.00
