spring:
  application:
    name: tellar-banking-bff
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
tellar:
  credit-balance:
    default-amount: 1000.00
